import box from '@mui/material/Box';
import drawer from '@mui/material/Drawer';
import button from '@mui/material/Button';
import list from '@mui/material/List';
import divider from '@mui/material/Divider';
import listitem from '@mui/material/ListItem';
import listitembutton from '@mui/material/ListItemButton';
import listitemicon from '@mui/material/ListItemIcon';
import listitemtext from '@mui/material/ListItemText';
import inboxicon from '@mui/icons-material/MoveToInbox';
import mailicon from '@mui/icons-material/Mail';
import container from '@mui/material/Container';
import grid from '@mui/material/Grid';
import paper from '@mui/material/Paper';

export	const	Box	=	box;
export	const	Drawer	=	drawer;
export	const	Button	=	button;
export	const	List	=	list;
export	const	Divider	=	divider;
export	const	ListItem	=	listitem;
export	const	ListItemButton	=	listitembutton;
export	const	ListItemIcon	=	listitemicon;
export	const	ListItemText	=	listitemtext;
export	const	InboxIcon	=	inboxicon;
export	const	MailIcon	=	mailicon;
export	const	Container	=	container;
export	const	Grid	=	grid;
export	const	Paper	=	paper;
